spring:
  cloud:
    gateway:
      routes:
        - id: usuarios-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/usuarios/**
        - id: tareas-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/tareas/**